###############################################################################
# РАЗДЕЛ:Базовые настройки
# ***
# SECTION:Basic settings
###############################################################################

###
# Будет ли демон сохранять правила в системный файл nftables.
# Не забудьте проверить, что путь к nftables соответствует вашей ОС.
# false = Выключает.
# true  = Включает.
#
# По умолчанию: false
# ***
# Will the daemon save rules to the system nftables file.
# Don't forget to check that the path to nftables matches your OS.
# false = Disables.
# true = Enables.
#
# Default: false
###
saves_rules = false

###
# Путь, где будут сохранены правила для nftables. Укажите путь, соответствующий вашей ОС.
#
# По умолчанию: /etc/nftables.conf
# ***
# Path where rules for nftables will be saved. Please specify the path specific to your OS.
#
# Default: /etc/nftables.conf
###
saves_rules_path = "/etc/nftables.conf"

###############################################################################
# РАЗДЕЛ:Политика действий по умолчанию
# ***
# SECTION:Default action policy
###############################################################################
[policy]
###
# Политика входящего трафика.
# Допустимые значения:
# drop   = блокировать без ответа
# reject = блокировка с ответом
# accept = разрешить
#
# По умолчанию: drop
# ***
# Inbound traffic policy.
# Acceptable values:
# drop   = block without response
# reject = block with response
# accept = allow
#
# Default: drop
###
input = "drop"

###
# Политика исходящего трафика.
# Допустимые значения:
# drop   = блокировать без ответа
# reject = блокировка с ответом
# accept = разрешить
#
# По умолчанию: drop
# ***
# Outgoing traffic policy.
# Acceptable values:
# drop   = block without response
# reject = block with response
# accept = allow
#
# Default: reject
###
output = "reject"

###
# Политика forward трафика.
# Допустимые значения:
# drop   = блокировать без ответа
# reject = блокировка с ответом
# accept = разрешить
#
# По умолчанию: drop
# ***
# Forward traffic policy.
# Acceptable values:
# drop   = block without response
# reject = block with response
# accept = allow
#
# Default: drop
###
forward = "drop"

###############################################################################
# РАЗДЕЛ:Именование метаданных
# ***
# SECTION:Metadata Naming
###############################################################################
[metadataNaming]
###
# Имя таблицы в nftables
# По умолчанию: "shield"
# ***
# Table name in nftables
# Default: "shield"
###
table_name = "shield"

###
# Имя chain для input
# По умолчанию: "input"
# ***
# Chain name for input
# Default: "input"
###
chain_input_name = "input"

###
# Имя chain для output
# По умолчанию: "output"
# ***
# Chain name for output
# Default: "output"
###
chain_output_name = "output"

###
# Имя chain для forward
# По умолчанию: "forward"
# ***
# Chain name for forward
# Default: "forward"
###
chain_forward_name = "forward"