###############################################################################
# РАЗДЕЛ:Общие настройки
# ***
# SECTION:General Settings
###############################################################################
[options]
###
# Будет ли демон сохранять правила в системный файл nftables.
# Не забудьте проверить, что путь к nftables соответствует вашей ОС.
# По умолчанию: false
# ***
# Will the daemon save rules to the system nftables file.
# Don't forget to check that the path to nftables matches your OS.
# Default: false
###
saves_rules = false

###
# Путь, где будут сохранены правила для nftables. Укажите путь, соответствующий вашей ОС.
# По умолчанию: /etc/nftables.conf
# ***
# Path where rules for nftables will be saved. Please specify the path specific to your OS.
# Default: /etc/nftables.conf
###
saves_rules_path = "/etc/nftables.conf"

###
# Включите следующую опцию, если хотите применять строгие правила nftables к DNS-трафику
# (т.е. использовать отслеживание подключений nftables). Включение этой опции
# может вызвать проблемы с разрешением DNS как входящих, так и исходящих DNS-имен, но может помочь
# предотвратить злоупотребление локальным DNS-сервером.
# По умолчанию: false
###
# Enable the following option if you want to apply strict nftables rules to DNS
# traffic (i.e. relying on nftables connection tracking). Enabling this option
# could cause DNS resolution issues both to and from the server but could help
# prevent abuse of the local DNS server.
# Default: false
###
dns_strict = false

###
# Включите следующую опцию, если хотите применять строгие правила nftables к DNS
# трафику между сервером и серверами имён, указанными в /etc/resolv.conf
# Включение этой опции может вызвать проблемы с разрешением DNS как на сервер, так и с него
# но может помочь предотвратить злоупотребление локальным DNS-сервером.
# По умолчанию: false
###
# Enable the following option if you want to apply strict nftables rules to DNS
# traffic between the server and the nameservers listed in /etc/resolv.conf
# Enabling this option could cause DNS resolution issues both to and from the
# server but could help prevent abuse of the local DNS server.
# Default: false
###
dns_strict_ns = false

###
# Отбрасывать пакеты, нарушающие порядок поступления, а также пакеты в состоянии
# INVALID в системе отслеживания соединений nftables.
# По умолчанию: true
###
# Drop out of order packets and packets in an INVALID state in nftables connection tracking.
# Default: true
###
packet_filter = true

###############################################################################
# РАЗДЕЛ:Политика действий по умолчанию
# ***
# SECTION:Default action policy
###############################################################################
[policy]
###
# Политика входящего трафика.
# Допустимые значения:
# drop   = блокировать без ответа
# reject = блокировка с ответом
# accept = разрешить
#
# По умолчанию: drop
# ***
# Inbound traffic policy.
# Acceptable values:
# drop   = block without response
# reject = block with response
# accept = allow
#
# Default: drop
###
input = "drop"

###
# Политика исходящего трафика.
# Допустимые значения:
# drop   = блокировать без ответа
# reject = блокировка с ответом
# accept = разрешить
#
# По умолчанию: drop
# ***
# Outgoing traffic policy.
# Acceptable values:
# drop   = block without response
# reject = block with response
# accept = allow
#
# Default: reject
###
output = "reject"

###
# Политика forward трафика.
# Допустимые значения:
# drop   = блокировать без ответа
# reject = блокировка с ответом
# accept = разрешить
#
# По умолчанию: drop
# ***
# Forward traffic policy.
# Acceptable values:
# drop   = block without response
# reject = block with response
# accept = allow
#
# Default: drop
###
forward = "drop"

###############################################################################
# РАЗДЕЛ:Именование метаданных
# ***
# SECTION:Metadata Naming
###############################################################################
[metadataNaming]
###
# Имя таблицы в nftables
# По умолчанию: "shield"
# ***
# Table name in nftables
# Default: "shield"
###
table_name = "shield"

###
# Имя chain для input
# По умолчанию: "input"
# ***
# Chain name for input
# Default: "input"
###
chain_input_name = "input"

###
# Имя chain для output
# По умолчанию: "output"
# ***
# Chain name for output
# Default: "output"
###
chain_output_name = "output"

###
# Имя chain для forward
# По умолчанию: "forward"
# ***
# Chain name for forward
# Default: "forward"
###
chain_forward_name = "forward"